### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by DaveDischord** [TOLDOTECHNIK/TTBOUNCE#1]
Your library works great, and thanks for making it.  I was wondering, if its something that could be useful, if you could add a callback, or Boolean flag, when a button is released after attachPress is called?

**Comment by DaveDischord** [comment]
I went ahead and took a stab at implementing the Release callback.  Untested, but it was a straightforward setup, if you want to have a look.
[TTBOUNCE.zip](https://github.com/TOLDOTECHNIK/TTBOUNCE/files/2496395/TTBOUNCE.zip)

**Comment by TOLDOTECHNIK** [comment]
Hi DaveDischord,

Thanks for your effort! We just patched our code with your additions.

Regards
